### ISSUE TITLE
Transfer to Agenda org?

### ISSUE THREAD

**Issue by simison** [agenda/human-interval#13]
I know this package is really low maintenance but what do you think about moving this under [Agenda org](https://github.com/agenda)? Since that package quite heavily relies on this, it would be good to have push rights among same devs.

**Comment by simison** [comment]
Feel free to also just pass maintainer rights for me, I can take care of this repo a little bit for you. :-) <3

**Comment by fega** [comment]
@simison your fork will be used to agenda?

**Comment by simison** [comment]
@fega I'm not sure if I understand your question...

**Comment by fega** [comment]
@simison you have a fork of this repository, I asked if your intentions are improve it to use in the agenda package.

**Comment by simison** [comment]
@fega oh right. :-) That's just how GitHub works when you [send PRs to a repostory](https://github.com/rschmukler/human-interval/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Asimison): you gotta make a fork. :-) I or we definitely won't be using those for anything. Thanks for asking!

**Comment by OmgImAlexis** [comment]
@rschmukler could you please check this out when you have a chance.

**Comment by rschmukler** [comment]
Happy to transfer it over to the agenda org. Sorry on the delay! It's done!

**Comment by simison** [comment]
Awesome, thanks a bunch @rschmukler !

Remember to also pass rights to NPM package for @OmgImAlexis 

https://www.npmjs.com/package/human-interval

love <3
