### ISSUE TITLE
Does this need to be browser ready or shall we expect the user to bundle it?

### ISSUE THREAD

**Issue by OmgImAlexis** [agenda/human-interval#14]
@agenda/maintainers 

Is there much point in holding back with things like `const` and arrow function if we can live without them then we should try and make this work for all browsers if not I'd say we ditch first hand browser support and expect the user to bundle it.

**Comment by simison** [comment]
Good question.

I think we can expect people to bundle it since we haven't shipped `dist` folder anyway and this isn't available at Bower neither. So anyone who has been using this via browser should have been bundling all along.

**Comment by simison** [comment]
...and it's almost 2018 ;-) 🎆
