### ISSUE TITLE
Add @simison to NPM

### ISSUE THREAD

**Issue by simison** [agenda/human-interval#25]
Hello!

@rschmukler could you please add me to NPM for this package so that I could publish new versions? :-) Thanks!

**Comment by rschmukler** [comment]
@simison sorry on the delay! I've added you. Cheers!

**Comment by simison** [comment]
You rock!

Thanks. :-)

**Comment by simison** [comment]
Hmm, tried `npm publish` just now but I'm getting "no permission":

```
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You do not have permission to publish "human-interval". Are you logged in as the correct user? : human-interval
```

https://www.npmjs.com/package/human-interval

I'm https://www.npmjs.com/~simison on NPM

```
human-interval@0.1.6 | MIT | deps: none | versions: 7
Human readable time measurements
https://github.com/rschmukler/human-interval#readme

keywords: interval, time, date

dist
.tarball: https://registry.npmjs.org/human-interval/-/human-interval-0.1.6.tgz
.shasum: 0057973454764c3abcbeb2aed612fc9644e68488

maintainers:
- rschmukler <ryan@slingingcode.com>

dist-tags:
latest: 0.1.6

published over a year ago by rschmukler <ryan@slingingcode.com>
```

@rschmukler could you double check?

**Comment by rschmukler** [comment]
@simison so terribly sorry! I'm not sure what happened there, and of course I missed this. You *should* be added for real now. Please feel free to email me directly in the future if you don't get a quicker response on GitHub.

Cheers!

**Comment by simison** [comment]
Nice, was just able to do a 1.0.0 release. :-)

First one in 4 years! Yay!
