### ISSUE TITLE
Conflicting issues in running ava tests locally and in travis-ci

### ISSUE THREAD

**Issue by sampathBlam** [agenda/human-interval#32]
I recently cloned the repo, made some changes and tried to run the tests locally using the test script in package.json. 

When I ran the test using `npm run test` locally, it gave me an error 
**. import should occur before import of ava import/order**

Hence I changed the order of the import statements in `test.js` (Moved import off ava below import of .)

But when I submitted a PR, the travis-ci build failed stating the reason - 
**ava import should occur before import of .** 

Is there something we can do to make this uniform? Or am I missing something here?

**Comment by simison** [comment]
Not quite sure but currently it seems to be passing in both CI and localy.
