### ISSUE TITLE
(potential) bug with agenda.schedule

### ISSUE THREAD

**Issue by davidgruebl** [agenda/human-interval#5]
when working with agenda I ran into the following issue:

``` js
// works perfectly fine
agneda.every('90 seconds')
agenda.every('1.5 minutes')
agenda.every('1 minute and 30 seconds')
```

``` js
// works perfectly fine
agenda.schedule('in 90 seconds')
```

``` js
// does not work
// no error is thrown, the time saved in the database is incorrect though
agenda.schedule('in 1.5 minutes')
agenda.schedule('in 1 minute and 30 seconds')
```

I am not sure whether this is an rather a missing feature than a bug, it's definitely not expected, unintuitive

thanks a lot @rschmukler for your work on agenda and human-interval - it is an pleasure to use!

**Comment by simison** [comment]
I know I'm commenting on old issue but this should be closed here and re-opened at [Agenda repo](https://github.com/agenda/agenda/issues).
