### ISSUE TITLE
Use something like `node-numbered` to convert words in numbers

### ISSUE THREAD

**Issue by faridnsh** [agenda/human-interval#9]
Hello @rschmukler ,

To support more word numbers, instead of adding more data, we could use something like [`node-numbered`](https://github.com/blakeembrey/node-numbered) to do this and remove some code from the project while extending it's support. Would you be accepting such contribution? What do you think?

I suppose, to use that there needs to be a little bit of refactoring on how the code works. I'm thinking we could instead use the following algorithm:

1. Find the units in the string and split the string using them.
2. Pass the remaining strings to `node-numbered` which will convert them to numbers.
3. Process it and calculate the total.

**Comment by simison** [comment]
Hey @alFReD-NSH,

I think that's a great idea.

~Note that floats like ` 0.259` we will probably need to `Math.round()`.~ Actually nope! Should work just like that. Just need to check how many decimals is ok.

We've just recently moved this repo under @Agenda org. Would you feel like submitting a PR + tests for this? That would be sooooo helpful.
